out = [
    { name = "sep", amounts = [
        38.25,
        45.02,
        16.50,
        13.52,
        38.41,
        2.28,
        28.61,
        8.90,
        30.26,
        9.25
    ]},
    { name = "aug", amounts = [
        14.24,
        2.79,
        45.87,
        4.49,
        23.94,
        12.89,
        53.96,
        27.81,
        15.37,
        28.32,
        17.25,
        26.10,
        14.60
    ]},
]
