out = [
    { name = "aug", amounts = [
        14.24,
        2.79,
        45.87,
        4.49,
        23.94,
        12.89,
        53.96,
        27.81,
        15.37,
        28.32,
        17.25,
        26.10,
        14.60
    ]},
    { name = "jul", amounts = [
        15.39,
        32.26,
        16.17,
        31.76,
        10.11,
        22.17,
        3.78,
        36.73,
        21.27,
        38.15,
        8.46,
        33.06,
    ]},
    { name = "jun", amounts = [
        15.78,
        30.20,
        5.18,
        25.54,
        4.88,
        21,
        21.62,
        5.84,
        25.76,
        27.59,
        18.01,
        16.68,
        19.84,
        38.81,
        12.58
    ]}
]