out = [
    { name = "aug", amounts = [
        8.95,
        59.99,
        60,
        20.59,
        80.14,
        109.99,
        #528.00,
        55.98,
        33.97,
        5.45,
    ]},
    # { name = "jul", amounts = [
    #     120,
    #     84.90,
    #     10,
    #     10,
    #     60,
    #     34,
    #     80.13,
    #     23.95,
    #     6.29,
    #     50.50,
    #     49.98,
    #     79.99,
    #     10,
    #     10,
    #     10,
    #     10,
    #     7.35,
    #     768.52,
    #     60,
    #     79.97,
    #     1.35,
    #     69,
    #     30.93,
    #     10,
    #     10,
    #     35,
    #     999,
    #     12.19,     
    # ]},
    { name = "jun", amounts = [
        10,
        10,
        127.05,
        153.82,
        10,
        10,
        54.98,
        19.98,
        24.99,
        23.99,
        10,
        24.99,
        9.98,
        23.99,
        12.98,
        10,
    ]}
]